Presentation/SISAPI.API/Areas/Admin/Controllers/AcademicController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SISAPI.API.Areas.Admin.Models;
using SISAPI.Application.Repositories;
using SISAPI.Domain.Entities;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace SISAPI.API.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    public class AcademicController : Controller
    {
        private readonly IAcademicRepository _academicRepository;
        private readonly IFacultyRepository _facultyRepository;
        private IEnumerable<Faculty> Faculties { get; set; }

        public AcademicController(IAcademicRepository academicRepository, IFacultyRepository facultyRepository)
        {
            _academicRepository = academicRepository;
            _facultyRepository = facultyRepository;
            Faculties = _facultyRepository.GetAll();
        }

        public IActionResult Index()
        {
            return View(_academicRepository.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new AnnotationsAcademicModel(){ Faculties = Faculties });
        }

        [HttpPost]
        public IActionResult Create(AnnotationsAcademicModel model)
        {
            if (ModelState.IsValid)
            {
                Academic academic = new Academic()
                {
                    Mail = model.Mail,
                    Name = model.Name,
                    Surname = model.Surname,
                    Faculty = model.Faculty,
                    Department = model.Department
                };

                _academicRepository.AddAsync(academic);
                _academicRepository.SaveAsync();

                return RedirectToAction(nameof(Create));
            }
            else
            {
                model.Faculties = Faculties;
                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Detail(short id)
        {
            Academic academic = await _academicRepository.GetByIdAsync(id);

            AnnotationsAcademicModel model = new AnnotationsAcademicModel()
            {
                AcademicianId = academic.AcademicianId,
                Mail = academic.Mail,
                Name = academic.Name,
                Surname = academic.Surname,
                Faculty = academic.Faculty,
                Department = academic.Department,
                Faculties = Faculties
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Detail(AnnotationsAcademicModel model)
        {
            if (ModelState.IsValid)
            {
                Academic academic = await _academicRepository.GetByIdAsync(model.AcademicianId);
                academic.Name = model.Name;
                academic.Surname = model.Surname;
                academic.Mail = model.Mail;
                academic.Faculty = model.Faculty;
                academic.Department = model.Department;
                await _academicRepository.SaveAsync();

            }
            model.Faculties = Faculties;
            return View(model);
        }

        public async Task<IActionResult> Delete(short academic_id)
        {
            await _academicRepository.RemoveAsync(academic_id);
            await _academicRepository.SaveAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

Presentation/SISAPI.API/Areas/Admin/Controllers/LessonController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SISAPI.API.Areas.Admin.Models;
using SISAPI.Application.Repositories;
using SISAPI.Domain.Entities;
using System.Threading.Tasks;

namespace SISAPI.API.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]

    public class LessonController : Controller
    {
        private readonly ILessonRepository _lessonRepository;
        public LessonController(ILessonRepository lessonRepository)
        {
            _lessonRepository = lessonRepository;
        }
        public IActionResult Index()
        {
            return View(_lessonRepository.GetAll());
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            Lesson lesson = await _lessonRepository.GetByIdAsync(short.Parse(id));

            if (lesson != null)
            {
                return View(new AnnotationsLessonModel()
                {
                    LessonId = lesson.LessonId,
                    LessonCode = lesson.LessonCode,
                    LessonName = lesson.LessonName,
                    LessonType = lesson.LessonType,
                    Ects = lesson.Ects,
                    Credit = lesson.Credit,
                    Semester = lesson.Semester,
                    GradeLevel = lesson.GradeLevel,
                    TheoreticalLimit = lesson.TheoreticalLimit,
                    PraticalLimit = lesson.PraticalLimit,
                    LecturerId = lesson.LecturerId,
                });
            }
            else
            {
                return NotFound();
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(AnnotationsLessonModel model)
        {
            if (ModelState.IsValid)
            {
                Lesson lesson = await _lessonRepository.GetByIdAsync(model.LessonId);
                lesson.LessonCode = model.LessonCode;
                lesson.LessonName = model.LessonName;
                lesson.LessonType = model.LessonType;
                lesson.Ects = model.Ects;
                lesson.Credit = model.Credit;
                lesson.Semester = model.Semester;
                lesson.GradeLevel = model.GradeLevel;
                lesson.TheoreticalLimit = model.TheoreticalLimit;
                lesson.PraticalLimit = model.PraticalLimit;
                lesson.LecturerId = model.LecturerId;
                await _lessonRepository.SaveAsync();
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new AnnotationsLessonModel());
        }

        [HttpPost]
        public IActionResult Create(AnnotationsLessonModel model)
        {
            if (ModelState.IsValid)
            {
                Lesson lesson = new Lesson() {
                    LessonName = model.LessonName,
                    LessonCode = model.LessonCode,
                    LessonType = model.LessonType,
                    Credit = model.Credit,
                    Semester = model.Semester,
                    GradeLevel = model.GradeLevel,
                    TheoreticalLimit = model.TheoreticalLimit,
                    PraticalLimit = model.PraticalLimit,
                    Ects = model.Ects,
                    LecturerId = model.LecturerId
                };

                _lessonRepository.AddAsync(lesson);
                _lessonRepository.SaveAsync();

                return RedirectToAction(nameof(Create));
            }

            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int lesson_id)
        {
            await _lessonRepository.RemoveAsync(lesson_id);
            await _lessonRepository.SaveAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Presentation/SISAPI.API/Areas/Admin/Views/Lesson/Create.cshtml
@model AnnotationsLessonModel

@{
    Layout = "_AdminMainLayout";
}

<div id="back-to-div">
    <a asp-action="Index" class="btn btn-outline-dark m-4">Dersler Listesine Geri Dön</a>
</div>

<div id="student-create-area" class="container">
    <div>
        <h3 class="text-center noselect">Yeni Ders Ekle</h3>
        <hr style="border: 3px solid #000;">
    </div>
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group mt-3">
            <label asp-for="LessonName" class="control-label">Ders Adı</label>
            <input asp-for="LessonName" class="form-control" />
            <span asp-validation-for="LessonName" class="text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="LessonCode" class="control-label">Ders Kodu</label>
            <input asp-for="LessonCode" class="form-control" />
            <span asp-validation-for="LessonCode" class="text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="LessonType" class="control-label">Ders Tipi</label>
            <select asp-for="LessonType" class="form-control">
                <option selected value="Seçmeli">Seçmeli</option>
                <option value="Zorunlu">Zorunlu</option>
            </select>

        </div>
        <div class="form-group mt-3">
            <label asp-for="Ects" class="control-label">AKTS</label>
            <input asp-for="Ects" type="text" class="form-control" />
            <span asp-validation-for="Ects" class="text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="Credit" class="control-label">Kredi</label>
            <input asp-for="Credit" type="text" class="form-control" />
            <span asp-validation-for="Credit" class="text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="Semester" class="control-label">Dönem</label>
            <select asp-for="Semester" class="form-control">
                <option selected value="Bahar">Bahar</option>
                <option value="Güz">Güz</option>
            </select>
            <span asp-validation-for="Semester" class="text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="GradeLevel" class="control-label">Sınıf</label>
            <input asp-for="GradeLevel" type="text" class="form-control" />
            <span asp-validation-for="GradeLevel" class="text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="PraticalLimit" class="control-label">Pratik Devamsızlık Limiti</label>
            <input asp-for="PraticalLimit" type="text" class="form-control" />
            <span asp-validation-for="PraticalLimit" class="text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="TheoreticalLimit" class="control-label">Teorik Devamsızlık Limiti</label>
            <input asp-for="TheoreticalLimit" type="text" class="form-control" />
            <span asp-validation-for="TheoreticalLimit" class="text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="LecturerId" class="control-label">Eğitmen Id</label>
            <input asp-for="LecturerId" type="text" class="form-control" />
            <span asp-validation-for="LecturerId" class="text-danger"></span>
        </div>
        <div class="d-grid form-group mt-3">
            <button class="btn btn-primary">Dersi Ekle</button>
        </div>
    </form>
</div>

<br />
<br />
<br />

<script>
    let active_index = 4
</script>

Presentation/SISAPI.API/Areas/Admin/Views/Lesson/Edit.cshtml
@model AnnotationsLessonModel

@{
    Layout = "_AdminMainLayout";
}

<div id="back-to-div">
    <a asp-action="Index" class="btn btn-outline-dark m-4">Dersler Listesine Geri Dön</a>
</div>

<div id="student-create-area" class="container">
    <div>
        <h3 class="text-center noselect">Ders Bilgileri Güncelle</h3>
        <hr style="border: 3px solid #000;">
    </div>
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group mt-3">
            <label class="control-label">Ders Id</label>
            <input readonly value="@Model.LessonId" class="form-control" asp-for="LessonId" />
        </div>
        <div class="form-group mt-3">
            <label asp-for="LessonName" class="control-label">Ders Adı</label>
            <input asp-for="LessonName" class="form-control" />
            <span asp-validation-for="LessonName" class="text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="LessonCode" class="control-label">Ders Kodu</label>
            <input asp-for="LessonCode" class="form-control" />
            <span asp-validation-for="LessonCode" class="text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="LessonType" class="control-label">Ders Tipi</label>
            @if (Model.LessonType.Equals("Seçmeli"))
            {
                <select asp-for="LessonType" class="form-control">
                    <option selected value="Seçmeli">Seçmeli</option>
                    <option value="Zorunlu">Zorunlu</option>
                </select>
            }
            else
            {
                <select asp-for="LessonType" class="form-control">
                    <option value="Seçmeli">Seçmeli</option>
                    <option selected value="Zorunlu">Zorunlu</option>
                </select>
            }

        </div>
        <div class="form-group mt-3">
            <label asp-for="Ects" class="control-label">AKTS</label>
            <input asp-for="Ects" type="text" class="form-control" />
            <span asp-validation-for="Ects" class="text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="Credit" class="control-label">Kredi</label>
            <input asp-for="Credit" type="text" class="form-control" />
            <span asp-validation-for="Credit" class="text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="Semester" class="control-label">Dönem</label>
            @if (Model.LessonType.Equals("Bahar"))
            {
                <select asp-for="Semester" class="form-control">
                    <option selected value="Bahar">Bahar</option>
                    <option value="Güz">Güz</option>
                </select>
            }
            else
            {
                <select asp-for="Semester" class="form-control">
                    <option value="Bahar">Bahar</option>
                    <option selected value="Güz">Güz</option>
                </select>
            }
            <span asp-validation-for="Semester" class="text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="GradeLevel" class="control-label">Sınıf</label>
            <input asp-for="GradeLevel" type="text" class="form-control" />
            <span asp-validation-for="GradeLevel" class="text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="PraticalLimit" class="control-label">Pratik Devamsızlık Limiti</label>
            <input asp-for="PraticalLimit" type="text" class="form-control" />
            <span asp-validation-for="PraticalLimit" class="text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="TheoreticalLimit" class="control-label">Teorik Devamsızlık Limiti</label>
            <input asp-for="TheoreticalLimit" type="text" class="form-control" />
            <span asp-validation-for="TheoreticalLimit" class="text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="LecturerId" class="control-label">Eğitmen Id</label>
            <input asp-for="LecturerId" type="text" class="form-control" />
            <span asp-validation-for="LecturerId" class="text-danger"></span>
        </div>
        <div class="d-grid form-group mt-3 mb-3">
            <button class="btn btn-primary">Kaydet</button>
        </div>
    </form>

    <hr />

    <form asp-area="Admin" asp-controller="Lesson" asp-action="Delete" method="get">
        <div class="form-group mt-3">
            <label class="control-label">Ders Id</label>
            <input readonly type="text" name="lesson_id" class="form-control" value="@Model.LessonId"/>
        </div>

        <div class="d-grid form-group mt-3">
            <button asp-action="Delete" class="btn btn-danger">Dersi Sil</button>
        </div>

    </form>
</div>

<br />
<br />
<br />

<script>
    let active_index = 4
</script>

Presentation/SISAPI.API/Areas/Admin/Views/Lesson/Index.cshtml
@model IEnumerable<Lesson>

@{
    Layout = "_AdminMainLayout";
}

<div id="lesson-search-area" class="search-area mt-3">
    <a asp-area="Admin" asp-action="Create" class="btn btn-outline-primary">Yeni Ders Ekle</a>
    <div class="input-group">
        <input class="form-control search-input" type="search" placeholder="Ders Id">
        <button class="btn btn-outline-success search-button" type="button">Ara</button>
    </div>
</div>

 <div class="container mt-5">

     <table class="table table-light table-hover">
         <thead class="table-dark noselect">
             <tr class="lh-50">
                 @*<th class="text-c" scope="col">Ders Id</th>*@
                 <th class="text-c" scope="col">Ders Kodu</th>
                 <th scope="col">Ders Adı</th>
                 <th class="text-c" scope="col">Ders Tipi</th>
                 <th class="text-c" scope="col">AKTS</th>
                 <th class="text-c" scope="col">Kredi</th>
                 <th class="text-c" scope="col">Dönem</th>
                 <th class="text-c" scope="col">Sınıf</th>
                 <th class="text-c" scope="col">TDL</th>
                 <th class="text-c" scope="col">PDL</th>
                 <th class="text-c" scope="col">Eğitmen Id</th>
             </tr>
         </thead>
         <tbody>
             @foreach (Lesson lesson in Model)
             {
                 <tr id="@lesson.LessonId">
                     <th class="text-c">
                         <a asp-area="Admin" asp-action="Edit" asp-route-id="@lesson.LessonId">
                             @lesson.LessonCode
                         </a>
                     </th>

                     <td>@lesson.LessonName</td>
                     <td class="text-c">@lesson.LessonType</td>
                     <td class="text-c">@lesson.Ects</td>
                     <td class="text-c">@lesson.Credit</td>
                     <td class="text-c">@lesson.Semester</td>
                     <td class="text-c">@lesson.GradeLevel</td>
                     <td class="text-c">@lesson.TheoreticalLimit</td>
                     <td class="text-c">@lesson.PraticalLimit</td>
                     <td class="text-c">
                         <a asp-area="Admin" asp-controller="Academic" asp-action="Detail" asp-route-id="@lesson.LecturerId">
                             @lesson.LecturerId
                         </a>
                     </td>
                     
                 </tr>
             }
         </tbody>
     </table>

 </div>



<script>
    let active_index = 4
    var base = `${window.location.origin}/Admin/Lesson`;
</script>