Presentation/SISAPI.API/Areas/Admin/Controllers/AcademicController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SISAPI.API.Areas.Admin.Models;
using SISAPI.Application.Repositories;
using SISAPI.Domain.Entities;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace SISAPI.API.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    public class AcademicController : Controller
    {
        private readonly IAcademicRepository _academicRepository;
        private readonly IFacultyRepository _facultyRepository;
        private IEnumerable<Faculty> Faculties { get; set; }

        public AcademicController(IAcademicRepository academicRepository, IFacultyRepository facultyRepository)
        {
            _academicRepository = academicRepository;
            _facultyRepository = facultyRepository;
            Faculties = _facultyRepository.GetAll();
        }

        public IActionResult Index()
        {
            return View(_academicRepository.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new AnnotationsAcademicModel(){ Faculties = Faculties });
        }

        [HttpPost]
        public IActionResult Create(AnnotationsAcademicModel model)
        {
            if (ModelState.IsValid)
            {
                Academic academic = new Academic()
                {
                    Mail = model.Mail,
                    Name = model.Name,
                    Surname = model.Surname,
                    Faculty = model.Faculty,
                    Department = model.Department
                };

                _academicRepository.AddAsync(academic);
                _academicRepository.SaveAsync();

                return RedirectToAction(nameof(Create));
            }
            else
            {
                model.Faculties = Faculties;
                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Detail(short id)
        {
            Academic academic = await _academicRepository.GetByIdAsync(id);

            AnnotationsAcademicModel model = new AnnotationsAcademicModel()
            {
                AcademicianId = academic.AcademicianId,
                Mail = academic.Mail,
                Name = academic.Name,
                Surname = academic.Surname,
                Faculty = academic.Faculty,
                Department = academic.Department,
                Faculties = Faculties
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Detail(AnnotationsAcademicModel model)
        {
            if (ModelState.IsValid)
            {
                Academic academic = await _academicRepository.GetByIdAsync(model.AcademicianId);
                academic.Name = model.Name;
                academic.Surname = model.Surname;
                academic.Mail = model.Mail;
                academic.Faculty = model.Faculty;
                academic.Department = model.Department;
                await _academicRepository.SaveAsync();

            }
            model.Faculties = Faculties;
            return View(model);
        }

        public async Task<IActionResult> Delete(short academic_id)
        {
            await _academicRepository.RemoveAsync(academic_id);
            await _academicRepository.SaveAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

Presentation/SISAPI.API/Areas/Admin/Controllers/LessonController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SISAPI.API.Areas.Admin.Models;
using SISAPI.Application.Repositories;
using SISAPI.Domain.Entities;
using System.Threading.Tasks;

namespace SISAPI.API.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]

    public class LessonController : Controller
    {
        private readonly ILessonRepository _lessonRepository;
        public LessonController(ILessonRepository lessonRepository)
        {
            _lessonRepository = lessonRepository;
        }
        public IActionResult Index()
        {
            return View(_lessonRepository.GetAll());
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            Lesson lesson = await _lessonRepository.GetByIdAsync(short.Parse(id));

            if (lesson != null)
            {
                return View(new AnnotationsLessonModel()
                {
                    LessonId = lesson.LessonId,
                    LessonCode = lesson.LessonCode,
                    LessonName = lesson.LessonName,
                    LessonType = lesson.LessonType,
                    Ects = lesson.Ects,
                    Credit = lesson.Credit,
                    Semester = lesson.Semester,
                    GradeLevel = lesson.GradeLevel,
                    TheoreticalLimit = lesson.TheoreticalLimit,
                    PraticalLimit = lesson.PraticalLimit,
                    LecturerId = lesson.LecturerId,
                });
            }
            else
            {
                return NotFound();
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(AnnotationsLessonModel model)
        {
            if (ModelState.IsValid)
            {
                Lesson lesson = await _lessonRepository.GetByIdAsync(model.LessonId);
                lesson.LessonCode = model.LessonCode;
                lesson.LessonName = model.LessonName;
                lesson.LessonType = model.LessonType;
                lesson.Ects = model.Ects;
                lesson.Credit = model.Credit;
                lesson.Semester = model.Semester;
                lesson.GradeLevel = model.GradeLevel;
                lesson.TheoreticalLimit = model.TheoreticalLimit;
                lesson.PraticalLimit = model.PraticalLimit;
                lesson.LecturerId = model.LecturerId;
                await _lessonRepository.SaveAsync();
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new AnnotationsLessonModel());
        }

        [HttpPost]
        public IActionResult Create(AnnotationsLessonModel model)
        {
            if (ModelState.IsValid)
            {
                Lesson lesson = new Lesson() {
                    LessonName = model.LessonName,
                    LessonCode = model.LessonCode,
                    LessonType = model.LessonType,
                    Credit = model.Credit,
                    Semester = model.Semester,
                    GradeLevel = model.GradeLevel,
                    TheoreticalLimit = model.TheoreticalLimit,
                    PraticalLimit = model.PraticalLimit,
                    Ects = model.Ects,
                    LecturerId = model.LecturerId
                };

                _lessonRepository.AddAsync(lesson);
                _lessonRepository.SaveAsync();

                return RedirectToAction(nameof(Create));
            }

            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int lesson_id)
        {
            await _lessonRepository.RemoveAsync(lesson_id);
            await _lessonRepository.SaveAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Presentation/SISAPI.API/Areas/Admin/Controllers/StudentController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SISAPI.API.Areas.Admin.Models;
using SISAPI.Application.Repositories;
using SISAPI.Domain.Entities;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;

namespace SISAPI.API.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    public class StudentController : Controller
    {
        private readonly IStudentRepository _studentRepository;
        private readonly IAcademicRepository _academicRepository;
        private readonly IFacultyRepository _facultyRepository;
        private readonly INoteRepository _noteRepository;
        private IEnumerable<Faculty> Faculties { get; set; }
        public StudentController(IStudentRepository studentRepository, IAcademicRepository academicRepository, INoteRepository noteRepository, IFacultyRepository facultyRepository)
        {
            _studentRepository = studentRepository;
            _academicRepository = academicRepository;
            _facultyRepository = facultyRepository;
            _noteRepository = noteRepository;
            Faculties = _facultyRepository.GetAll();
        }
        public IActionResult Index()
        {
            return View(_studentRepository.GetAll());
        }


        [HttpGet]
        public async Task<IActionResult> Detail(string id)
        {
            StudentDetailModel model = await GetStudentDetailModel(id);
            SetSession("student_no", id);
            model.Faculties = Faculties;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Detail(StudentDetailModel model, IFormCollection collection)
        {
            if (ModelState.IsValid)
            {
                if (!collection.Keys.Contains("student.StudentNo")) // Öğrenci bilgilerini içermiyorsa (Not bilgilerini içerir)
                {
                    foreach (string key in collection.Keys)
                    {
                        if (key != "__RequestVerificationToken")
                        {
                            await UpdateNote(key, collection[key]);
                        }
                    }
                }
                else // Sadece Öğrenci bilgilerini içerir (Not bilgilerini içermez)
                {
                    Student student = await _studentRepository.GetByIdAsync(model.student.StudentNo);
                    student.Name = model.student.Name;
                    student.Surname = model.student.Surname;
                    student.Department = model.student.Department;
                    student.Faculty = model.student.Faculty;
                    student.GradeLevel = model.student.GradeLevel;
                    student.AdvisorId = model.student.AdvisorId;
                    await _studentRepository.SaveAsync();
                }

                return RedirectToAction("Detail", new { id = GetSession("student_no") });
            }
            else
            {
                StudentDetailModel default_model = await GetStudentDetailModel(model.student.StudentNo);

                model.notes = default_model.notes;
                model.academics = default_model.academics;
                model.academician = default_model.academician;
                model.Faculties = Faculties;
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new AnnotationsStudentModel() { Faculties = Faculties });
        }

        [HttpPost]
        public async Task<IActionResult> Create(AnnotationsStudentModel model)
        {
            if (ModelState.IsValid)
            {
                await _studentRepository.AddAsync(new Student() {
                    StudentNo = model.StudentNo,
                    Name = model.Name,
                    Surname = model.Surname,
                    Faculty = model.Faculty,
                    Department = model.Department,
                    GradeLevel = model.GradeLevel,
                    AdvisorId = model.AdvisorId
                });
                await _studentRepository.SaveAsync();
                return Redirect($"Index#{model.StudentNo}");
            }
            model.Faculties = Faculties;
            return View(model);
        }

        public IActionResult Search(string number)
        {
            return RedirectToAction();
        }

        private async Task<StudentDetailModel> GetStudentDetailModel(string id)
        {
            Student student = await _studentRepository.GetByIdAsync(id, false);
            IEnumerable<Note> notes = _noteRepository.GetWhere(n => n.Period == Program.Period && n.StudentNo == student.StudentNo, false);
            IEnumerable<Academic> academics = _academicRepository.GetWhere(a => a.Department == student.Department, false);
            Academic academician = null;

            if (student.AdvisorId != null)
            {
                academician = await _academicRepository.GetByIdAsync((short)student.AdvisorId, false);
            }

            StudentDetailModel model = new StudentDetailModel()
            {
                student = new AnnotationsStudentModel()
                {
                    StudentNo = student.StudentNo,
                    Name = student.Name,
                    Surname = student.Surname,
                    AdvisorId = student.AdvisorId,
                    Department = student.Department,
                    Faculty = student.Faculty,
                    GradeLevel = student.GradeLevel
                },
                notes = notes,
                academician = academician,
                academics = academics,
                Faculties = Faculties
            };

            return model;
        }

        private void SetSession(string key, string value)
        {
            HttpContext.Session.SetString(key, value);
        }

        private string GetSession(string key)
        {
            return HttpContext.Session.GetString(key);
        }

        private async Task<bool> UpdateNote(string key, string point)
        {
            string[] splitted_key = key.Split("-");
            string lesson_code = splitted_key[0];
            short lesson_id = short.Parse(splitted_key[1]);

            string student_no = GetSession("student_no");

            double? note_point = null;

            try
            {
                note_point = double.Parse(point);
            }
            catch (Exception e)
            {
                Debug.WriteLine(e.Message);
            }

            Note note = await _noteRepository.GetSingleAsync(n => n.StudentNo == student_no && n.LessonId == lesson_id && n.Period == Program.Period);

            if (note != null)
            {
                switch (lesson_code)
                {
                    case "mid": // Vize
                        note.MidtermExam = note_point;
                        break;

                    case "mk1": // Mazeret
                        note.MakeUpExam1 = note_point;
                        break;

                    case "fin": // Final
                        note.FinalExam = note_point;
                        break;

                    case "mk2": // Bütünleme
                        note.MakeUpExam2 = note_point;
                        break;

                    default:
                        return false;
                }
            }
            await _noteRepository.SaveAsync();
            return true;
        }
    }
}

Presentation/SISAPI.API/Areas/Admin/Views/Student/Detail.cshtml
@model StudentDetailModel

@{
    Layout = "_AdminMainLayout";
}

@if (Model.student != null)
{
    <div class="container-fluid row mx-auto mt-5">
        <div id="studentInfos">
            <form asp-area="Admin" asp-controller="Student" asp-action="Detail">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group mt-3">
                    <label class="control-label">Öğrenci Numarası</label>
                    <input class="form-control" readonly asp-for="@Model.student.StudentNo" />
                </div>
                <div class="form-group mt-3">
                    <label class="control-label">Ad</label>
                    <input asp-for="@Model.student.Name" class="form-control" />
                    <span asp-validation-for="@Model.student.Name" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label class="control-label">Soyad</label>
                    <input asp-for="@Model.student.Surname" class="form-control" />
                    <span asp-validation-for="@Model.student.Surname" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label class="control-label">Fakülte</label>
                    <select asp-for="@Model.student.Faculty" class="form-control">
                        @foreach (Faculty faculty in Model.Faculties)
                        {
                            <option value="@faculty.Name">@faculty.Name</option>
                        }
                    </select>
                    <span asp-validation-for="@Model.student.Faculty" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label class="control-label">Bölüm</label>
                    <input asp-for="@Model.student.Department" class="form-control" />
                    <span asp-validation-for="@Model.student.Department" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label class="control-label">Sınıf</label>
                    <input asp-for="@Model.student.GradeLevel" class="form-control" />
                    <span asp-validation-for="@Model.student.GradeLevel" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label class="control-label">Danışman</label>
                    @if (Model.academician != null)
                    {
                        <select asp-for="@Model.student.AdvisorId" class="form-select" aria-label="Default select example">
                            @foreach (Academic academic in Model.academics)
                            {
                                if (academic.AcademicianId == Model.academician.AcademicianId)
                                {
                                    <option value="@academic.AcademicianId" selected>@(Model.academician.Name + " " +  Model.academician.Surname)</option>
                                }
                                else
                                {
                                    <option value="@academic.AcademicianId">@(academic.Name + " " + academic.Surname)</option>
                                }
                            }
                        </select>
                    }
                    else
                    {
                        <input asp-for="@Model.student.AdvisorId" class="form-control"/>
                    }

                </div>
                <div class="d-grid form-group mt-3">
                    <button class="btn btn-primary" type="submit">Güncelle</button>
                </div>
            </form>
        </div>

        <div id="note-table-area">
            <form asp-area="Admin" asp-controller="Student" asp-action="Detail" method="post">
                <table class="table table-light table-hover note-details">
                    <thead class="table-dark noselect">
                        <tr>
                            <th class="vertical"><div class="vertical">Ders ID</div></th>
                            <th class="vertical"><div class="vertical">Vize</div></th>
                            <th class="vertical"><div class="vertical">Mazeret</div></th>
                            <th class="vertical"><div class="vertical">Final</div></th>
                            <th class="vertical"><div class="vertical">Bütünleme</div></th>
                            <th class="vertical"><div class="vertical">Ortalama</div></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Note note in Model.notes)
                        {
                            <tr id="#@note.LessonId">

                                <th scope="row">
                                    <a asp-area="Admin" asp-controller="Lesson" asp-action="Edit" asp-route-id="@note.LessonId">
                                        @note.LessonId
                                    </a>
                                </th>

                                @if (note.MidtermExam != null)
                                {
                                    <td>
                                        <input autocomplete="off" class="form-control" name="mid-@note.LessonId" value="@note.MidtermExam" />
                                    </td>
                                }
                                else
                                {
                                    <td></td>
                                }

                                @if (note.MakeUpExam1 != null)
                                {
                                    <td>
                                        <input autocomplete="off" class="form-control" name="mk1-@note.LessonId" value="@note.MakeUpExam1" />
                                    </td>
                                }
                                else
                                {
                                    <td></td>
                                }
                                @if (note.FinalExam != null)
                                {
                                    <td>
                                        <input autocomplete="off" class="form-control" name="fin-@note.LessonId" value="@note.FinalExam" />
                                    </td>
                                }
                                else
                                {
                                    <td></td>
                                }
                                @if (note.MakeUpExam2 != null)
                                {
                                    <td>
                                        <input autocomplete="off" class="form-control" name="mk2-@note.LessonId" value="@note.MakeUpExam2" />
                                    </td>
                                }
                                else
                                {
                                    <td></td>
                                }
                                <th name="avg-@note.LessonId">@note.Average</th>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="d-grid">
                    <button class="btn btn-danger" type="submit">Notları Kaydet</button>
                </div>
            </form>
        </div>
    </div>
}

@*<div>
    <a asp-action="Index">Back to List</a>
</div>*@

<script>
    let active_index = 2
</script>

Presentation/SISAPI.API/Areas/Admin/Views/Student/Details.cshtml
@model StudentDetailModel

@{
    ViewData["Title"] = "StudentDetail";
    Layout = "_AdminMainLayout";
}
@if (Model.student != null)
{
    <div class="container-fluid row mx-auto mt-5">
        <div id="studentInfos">
            <form asp-area="Admin" asp-controller="Student" asp-action="Details">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group mt-3">
                    <label class="control-label">Öğrenci Numarası</label>
                    <input class="form-control" readonly asp-for="@Model.student.StudentNo" />
                </div>
                <div class="form-group mt-3">
                    <label class="control-label">Ad</label>
                    <input asp-for="@Model.student.Name" class="form-control" />
                    <span asp-validation-for="@Model.student.Name" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label class="control-label">Soyad</label>
                    <input asp-for="@Model.student.Surname" class="form-control" />
                    <span asp-validation-for="@Model.student.Surname" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label class="control-label">Fakülte</label>
                    <input asp-for="@Model.student.Faculty" class="form-control" />
                    <span asp-validation-for="@Model.student.Faculty" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label class="control-label">Bölüm</label>
                    <input asp-for="@Model.student.Department" class="form-control" />
                    <span asp-validation-for="@Model.student.Department" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label class="control-label">Sınıf</label>
                    <input asp-for="@Model.student.GradeLevel" class="form-control" />
                    <span asp-validation-for="@Model.student.GradeLevel" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <label class="control-label">Danışman</label>
                    <select asp-for="@Model.student.AdvisorId" class="form-select" aria-label="Default select example">
                        @foreach (Academic academic in Model.academics)
                        {
                            @if (academic.AcademicianId == Model.academician.AcademicianId)
                            {
                                <option value="@academic.AcademicianId" selected>@(Model.academician.Name + " " +  Model.academician.Surname)</option>
                            }
                            else
                            {
                                <option value="@academic.AcademicianId">@(academic.Name + " " + academic.Surname)</option>
                            }

                        }
                    </select>
                </div>
                <div class="d-grid form-group mt-3">
                    <button class="btn btn-primary" type="submit">Güncelle</button>
                </div>
            </form>
        </div>

        <div id="note-table-area">
            <form asp-area="Admin" asp-controller="Student" asp-action="Details" method="post">
                <table class="table table-light table-hover note-details">
                    <thead class="table-dark noselect">
                        <tr>
                            <th class="vertical"><div class="vertical">Ders ID</div></th>
                            <th class="vertical"><div class="vertical">Vize</div></th>
                            <th class="vertical"><div class="vertical">Mazeret</div></th>
                            <th class="vertical"><div class="vertical">Final</div></th>
                            <th class="vertical"><div class="vertical">Bütünleme</div></th>
                            <th class="vertical"><div class="vertical">Ortalama</div></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Note note in Model.notes)
                        {
                            <tr id="#@note.LessonId">

                                <th scope="row">
                                    <a asp-action="Lessons" asp-route-id="@note.LessonId">
                                        @note.LessonId
                                    </a>
                                </th>

                                @if (note.MidtermExam != null)
                                {
                                    <td>
                                        <input autocomplete="off" class="form-control" name="mid-@note.LessonId" value="@note.MidtermExam" />
                                    </td>
                                }
                                else
                                {
                                    <td></td>
                                }

                                @if (note.MakeUpExam1 != null)
                                {
                                    <td>
                                        <input autocomplete="off" class="form-control" name="mk1-@note.LessonId" value="@note.MakeUpExam1" />
                                    </td>
                                }
                                else
                                {
                                    <td></td>
                                }
                                @if (note.FinalExam != null)
                                {
                                    <td>
                                        <input autocomplete="off" class="form-control" name="fin-@note.LessonId" value="@note.FinalExam" />
                                    </td>
                                }
                                else
                                {
                                    <td></td>
                                }
                                @if (note.MakeUpExam2 != null)
                                {
                                    <td>
                                        <input autocomplete="off" class="form-control" name="mk2-@note.LessonId" value="@note.MakeUpExam2" />
                                    </td>
                                }
                                else
                                {
                                    <td></td>
                                }
                                <th name="avg-@note.LessonId">@note.Average</th>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="d-grid">
                    <button class="btn btn-danger" type="submit">Notları Kaydet</button>
                </div>
            </form>
        </div>
    </div>
}

@*<div>
    <a asp-area="Admin" asp-controller="Student" asp-action="Index">Back to List</a>
</div>*@

<script>
    let active_index = 2
</script>